# Assignment 3

# Problem 1

In [10]:
try:
    5/0
except ZeroDivisionError:
    print("Zero Division Error")
except e:
    print("Exception occurred")

Zero Division Error


In [11]:
def compute(num):
    try:
        num/0
    except:
        print("Number divide by zero")

In [12]:
compute(5)

Number divide by zero


# Problem 2

In [14]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for sub in subjects:
    for verb in verbs:
        for obj in objects:
            print(f'{sub} {verb} {obj}')

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Problem 3

In [16]:
import numpy as np
   
def generateVanderMatrix(vector, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in vector for i in range(n)]).reshape(vector.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in vector for i in range(n)]).reshape(vector.size,n)
    
    return op_matx

print("------------OUTPUT-------------\n")

input_data = np.array([1,2,3,4,5])
no_col_opmat = 3
op_matx_dec_order = generateVanderMatrix(input_data,no_col_opmat,False)
op_matx_inc_order = generateVanderMatrix(input_data,no_col_opmat,True)

print("The input array is:",input_data,"\n")
print("Number of columns in output matrix should be:",no_col_opmat,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_inc_order,"\n")
    

------------OUTPUT-------------

The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 

